#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

# command not found 발생할 경우 아래 export를 해주면 된다.
# export PATH="$PATH:/c/Program Files/dotnet"

dotnet format GA1_project_2d.sln --verify-no-changes --include Assets/02.Scripts
